### ISSUE TITLE
Ios Support 

### ISSUE THREAD

**Issue by PXshadow** [wikiti/extension-networking#7]
Hey sorry to ask again for support but I'm just curious if ios does works as a client.  I'm testing my project in an ios simulator and looking at the network support it shows that it does indeed have a connection to the server and how it is sending packets however the server is not receiving them in the slightest. Also the server is getting connected and disconnected calls from the simulation. Any help would be very much apperciated 😄

**Comment by wikiti** [comment]
Hello PXshadow,

I'll try to check if iOS has support for  native sockets, at least on the client side. Since I don't own an iPhone nor iPad, I'll probably have to use some kind of emulator.

Best regards,
Daniel

**Comment by wikiti** [comment]
Hello again,

After talking with a friend which develops for iOS, I think that I cannot test and debug the support for iOS devices, since the iOS *simulator* requires at least one MAC.

I think that I'll try the android version and see if it works. Maybe it's an issue related to `mobile` targets.

Best regards,
Daniel

**Comment by PXshadow** [comment]
Android version 100% works based on my experience for the past month,  however I don't know about in a simulator.  I mean there is a possibility that ios is just not working because of the simulator and might not work on Android simulator as well.  I'll try to get the device team ID set up for Apple so I can test on an actual device.  Thanks for all of the help,  Joey.

**Comment by PXshadow** [comment]
Android version 100% works based on my experience for the past month,  however I don't know about in a simulator.  I mean there is a possibility that ios is just not working because of the simulator and might not work on Android simulator as well.  I'll try to get the device team ID set up for Apple so I can test on an actual device.  Thanks for all of the help,  Joey.

**Comment by PXshadow** [comment]
Hey @wikiti I've been able to test This library fully on ios it totally works so there is no issue here! Sorry to not close sooner.
