### ISSUE TITLE
Demo 'basic-example' crashes on neko when starting server

### ISSUE THREAD

**Issue by gmisail** [wikiti/extension-networking#8]
I am attempting to compile under Neko (`lime run neko`). When pressing the 'Server' button in the 'basic-example' demo, the application crashes with this error message:

```
Called from ? line 1
Called from ApplicationMain.hx line 79
Called from ApplicationMain.hx line 111
Called from lime/app/Application.hx line 267
Called from lime/_backend/native/NativeApplication.hx line 158
Called from a C function
Called from lime/_backend/native/NativeApplication.hx line 440
Called from lime/_macros/EventMacro.hx line 101
Called from openfl/display/Stage.hx line 221
Called from openfl/display/Stage.hx line 1048
Called from openfl/display/Stage.hx line 1201
Called from openfl/display/Stage.hx line 984
Called from openfl/display/Stage.hx line 1070
Called from openfl/display/DisplayObject.hx line 350
Called from a C function
Called from openfl/events/EventDispatcher.hx line 218
Called from networking/sessions/Session.hx line 226
Called from networking/utils/NetworkEventsQueue.hx line 47
Called from openfl/events/EventDispatcher.hx line 97
Called from openfl/events/EventDispatcher.hx line 218
Called from networking/sessions/Session.hx line 221
Called from /usr/local/lib/haxe/std/neko/_std/Std.hx line 34
Called from a C function
Called from <header> line 1
Called from networking/wrappers/SocketWrapper.hx line 210
Called from /usr/local/lib/haxe/std/neko/_std/sys/net/Socket.hx line 191
Uncaught exception - std@socket_peer
```

I am running on Mac OSX, using Haxe 3.4.

**Comment by wikiti** [comment]
Hello @gmisail64! Thank you for being interested on this library!

Could you please share more information about which versions of lime and openfl are you using? I'll try to give it a look as soon as I can.

**Comment by gmisail** [comment]
I am using version 2.9.1 of Lime and 3.6.1 of OpenFL.

**Comment by wikiti** [comment]
Hello @gmisail64!

I think that I've fixed the issue on [this pull request](https://github.com/wikiti/extension-networking/pull/9); you can now update your haxelib installation with:

````sh
haxelib install extension-networking 1.4.1
````

Could you please check if it's working for you?

**Comment by gmisail** [comment]
Demo 'basic-example' works perfectly. I am having issues with the 'tic-tac-toe' demo however.
```
NetworkLogger.hx:64: # NETWORK EVENT -- $ -- NETWORK_EVENT_INIT_SUCCESS -- { server => { info => 2938CC0C-3892-1E51-7F2B-7E455E43D63E (local), max_connections => 1, port => 9999, _session => [object Session], flash_policy_file_port => null, clients => [], _thread => { _on_start => null, _active => true, _mutex => { _mutex => { m => #abstract } }, _on_loop => #function:0, _on_stop => null }, ip => 0.0.0.0, _uuid => null, _mutex => { _mutex => { m => #abstract } } }, message => Binded to 0.0.0.0:9999. }
tic-tac-toe(1513,0x7fffaa3623c0) malloc: *** error for object 0x1022a9eef: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

Will this library possibly work with Haxeflixel, as they are both based off of OpenFL?

**Comment by wikiti** [comment]
@gmisail64 As far as I know, it should have no conflicts with Haxeflixel, so it should work properly.

About your error, it's working properly on Windows on _neko_ target. I'll try it tomorrow on a Ubuntu system and see if it's related to UNIX.

**Comment by wikiti** [comment]
@gmisail64 Oh, I just found [this thread](http://community.openfl.org/t/malloc-error-with-textfield-in-neko/7639/2) on the OpenFL forums. Does that help?

**Comment by gmisail** [comment]
I believe that is an issue on my end, and has nothing to do with the library. Great work by the way!
